language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homas_test;'
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
