language:
  - php
  - node_js

php:
  - 7.2

node_js:
  - 10

install:
  - yarn install --frozen-lockfile

before_script:
  - cp .env.travis .env
  - mv cypress.json.travis cypress.json
  - mysql -e 'create database homas_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - $(yarn bin)/cypress run

after_success:
    - bash <(curl -s https://codecov.io/bash)

## Cache composer bits
cache:
  npm: true
  directories:
    - $HOME/.composer/cache/files
    - ~/.cache
