name: Cypress tests

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

  workflow_run:
    workflows:
      - Compress images
    types: [completed]

jobs:

  init:
    runs-on: ubuntu-latest
    name: Initialisation

    outputs:
      cypress: ${{ steps.cypress.outputs.cypress }}

    steps:
      - name: Set cypress context
        id: cypress
        run: |
          echo "::set-output name=cypress::false"
          href=$(jq --raw-output .pull_request._links.self.href "${{ github.event_path }}")
          echo $href
          curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header 'content-type: application/json' $href | \
            jq --raw-output ".labels[].name" | \
            while IFS=$'\n' read -r label; do
              if [ "$label" == "cypress" ]; then
                echo "::set-output name=cypress::true"
              fi
            done

  cypress:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.cypress == 'true'

    name: Cypress tests (PHP ${{ matrix.php-version }})

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

