name: Cypress tests

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

  workflow_run:
    workflows:
      - Compress images
    types: [completed]

jobs:
  #############
  # Run cypress tests
  #############
  cypress:
    runs-on: ubuntu-latest
    name: Cypress tests (PHP ${{ matrix.php-version }})

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']

    steps:
      - name: Set cypress context
        run: |
          echo "cypress=false" >> $GITHUB_ENV
          echo "bla=false" >> $GITHUB_ENV
          PR=$(jq --raw-output .pull_request.self.href "${{ github.event }}")
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header 'content-type: application/json' $PR | \
            jq --raw-output .labels[].name | \
            while IFS=$'\n' read -r label; do
              if [ "$label" == "cypress" ]; then
                echo "cypress=true" >> $GITHUB_ENV
              fi
            done

      - name: Test
        if: env.cypress == 'true'
        run: echo $cypress

      - name: Test
        if: env.bla == 'true'
        run: echo $bla
